/*
  An example grammar file, used for testing and reference.

  Conditions surrounded by apostrophes (') are interpreted as regular expressions.
  Rest of the conditions are interpreted as references to other rules.
*/


variable
  : type word ';'
  ;


//Mark reserved word rules as keyword, to avoid ambiguous tokens.
keyword type
  : 'int'
  | 'float'
  | 'char'
  | 'bool'
  ;

word
  : '[a-zA-Z]+'
  ;


function_dec
  : type word '\(' parameters_dec '\)'
  ;


parameters_dec
  : parameter_dec
  | parameter_dec ',' parameters_dec
  ;


parameter_dec
  : type word
  ;
  
